[build]
base = "."
publish = "client/dist"
command = "node build.js && npm install && cd client && npm install && npm run build"
functions = "netlify/functions"

[[redirects]]
from = "/api/auth/login"
to = "/.netlify/functions/login"
status = 200

[[redirects]]
from = "/api/auth/*"
to = "/.netlify/functions/auth/:splat"
status = 200

[[redirects]]
from = "/api/cards"
to = "/.netlify/functions/cards"
status = 200

[[redirects]]
from = "/api/cards/*"
to = "/.netlify/functions/cards/:splat"
status = 200

[[redirects]]
from = "/api/orders"
to = "/.netlify/functions/orders"
status = 200

[[redirects]]
from = "/api/orders/*"
to = "/.netlify/functions/orders/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
