[build]
base = "."
publish = "client/dist"
command = "node build.js && npm install && cd client && npm install && npm run build"
functions = "netlify/functions"

# Direct function access
[[redirects]]
from = "/.netlify/functions/direct-register"
to = "/.netlify/functions/direct-register"
status = 200
force = true

[[redirects]]
from = "/.netlify/functions/db-setup"
to = "/.netlify/functions/db-setup"
status = 200
force = true

[[redirects]]
from = "/api/auth/test-register"
to = "/.netlify/functions/test-register"
status = 200
force = true

[[redirects]]
from = "/api/auth/register"
to = "/.netlify/functions/api/auth/register"
status = 200
force = true

[[redirects]]
from = "/api/auth/profile"
to = "/.netlify/functions/auth-profile"
status = 200
force = true

[[redirects]]
from = "/api/cards"
to = "/.netlify/functions/cards"
status = 200
force = true

[[redirects]]
from = "/api/cards/*"
to = "/.netlify/functions/cards/:splat"
status = 200
force = true

[[redirects]]
from = "/api/auth/login"
to = "/.netlify/functions/auth-login"
status = 200
force = true

[[redirects]]
from = "/api/auth/*"
to = "/.netlify/functions/auth/:splat"
status = 200

[[redirects]]
from = "/api/cards"
to = "/.netlify/functions/cards"
status = 200

[[redirects]]
from = "/api/cards/*"
to = "/.netlify/functions/cards/:splat"
status = 200

[[redirects]]
from = "/api/orders"
to = "/.netlify/functions/orders"
status = 200

[[redirects]]
from = "/api/orders/*"
to = "/.netlify/functions/orders/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = false

[[redirects]]
from = "/direct-test.html"
to = "/direct-test.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"
